### ISSUE TITLE
Bug(???) in web and matlab version

### ISSUE THREAD

**Issue by juliencarponcy** [ttumkaya/ContrastPlot_MATLAB#4]
[CSVtable.zip](https://github.com/ACCLAB/DABEST-Matlab/files/3734701/CSVtable.zip)

Hello, could you possibly tell me what's wrong with these files  ?
CSV generated from table by writetable(Csvtable,CSVfilename,'Delimiter',',')

Error Message in matlab :

Error using bootci>bootbca (line 265)
With 'type' equal to 'bca' (the default), BOOTCI uses JACKKNIFE internally. The call to JACKKNIFE failed with
function '@(x)nanmean(x)'. Try using a confidence interval type other than 'bca'.

Error in bootci (line 171)
        [ci,bootstat] = bootbca(obsstat,nboot,fun,alpha,weights,bootstrpOptions,data{:});

Error in bootmoes (line 15)
bci=bootci(10000, hm, vec)';

Error in FscatJit2 (line 170)
    [av(idx), moes, bci] = bootmoes(curDat);

Error in dabest (line 19)
    [ss] = FscatJit2(identifiers, data);

Caused by:
    Error using jackknife
    Too many input arguments.

**Comment by ttumkaya** [comment]
Thanks for your patience, Julien.

The csv file attached in your message ('2019-10-16_14-26-51_SNR_Bclust_Clusters-vs-Singles.csv') works just fine in DABEST-MATLAB (see below).

Please make sure that you are using the right command: 
`dabest('2019-10-16_14-26-51_SNR_Bclust_Clusters-vs-Singles.csv')`

As for the web version, there is a slight difference in how the web and MATLAB versions read input: DABEST-MATLAB reads the group names from the column named 'Identifiers', while the web tool treats the column headers as group names. So you'd need to re-format your data accordingly; or alternatively, you could copy paste the values from the csv file into the table provided in the web tool.

Hope this helps!
Tayfun

![TwoGroups](https://user-images.githubusercontent.com/9079513/67936207-51917000-fc06-11e9-846b-c8e034780bc8.png)

**Comment by neuroptics** [comment]
I'm having the same issue, I'll open a new one.
