### ISSUE TITLE
Issue with bootbca()

### ISSUE THREAD

**Issue by neuroptics** [ttumkaya/ContrastPlot_MATLAB#6]
Hey Tayfun,

Having the same issue as Juliencarponcy, unrelated to the input data. I'm guessing its a version issue.

With R2018b, using the sample data you provided, I get the following:

Command:
dabest('MultipleGroups_sample.csv');

Error:
Error using bootci>bootbca (line 265)
With 'type' equal to 'bca' (the default), BOOTCI uses JACKKNIFE internally. The call to JACKKNIFE failed with function '@(x)nanmean(x)'. Try using a confidence interval type other than 'bca'.

Error in bootci (line 171)
        [ci,bootstat] = bootbca(obsstat,nboot,fun,alpha,weights,bootstrpOptions,data{:});

Error in bootmoes (line 15)
bci=bootci(10000, hm, vec)';

Error in FscatJit2 (line 169)
    [av(idx), moes, bci] = bootmoes(curDat);

Error in dabest (line 19)
    [ss] = FscatJit2(identifiers, data);

Error in oEDT_timecourse_plot_v6 (line 942)
dabest('MultipleGroups_sample.csv');

Caused by:
    Error using jackknife
    Too many input arguments.

**Comment by ttumkaya** [comment]
Hi David,

Thank you for your message.

Interesting point about the version issue; however, I installed R2018b and tried running the same command, still cannot reproduce the error message you and @Juliencarponcy are getting (please see the attachment).

Just curious do you get this error only with R2018b? Also, is your DABEST-MATLAB package up to date with our GitHub repo?

Thanks,
Tayfun

![DABEST-MATLAB_Issue](https://user-images.githubusercontent.com/9079513/71656486-5a253480-2d76-11ea-9dcc-a121d66e90e0.png)

**Comment by neuroptics** [comment]
Hey Tayfun,

I tracked it down. The widely used spectral analysis toolbox, Chronux, has its own jackknife() function which was superseding the built-in version.  

For other Chronux users, there are two ways to fix this: 
- Remove the Chronux version from the path. 
- Rename it to something like jackknife_chrx(). Chronux calls its version of jackknife() only once, in a function called den_jack(). Change it there as well to avoid the conflict and maintain the functionality of chronux. I can't seem to find any calls to den_jack() so option 1 would probably be fine if den_jack() won't be used on its own.

Thanks!
David

**Comment by ttumkaya** [comment]
Hi David,

Thanks very much for getting to the bottom of this. This will be helpful to all Chronux users!

Best,
Tayfun
