### ISSUE TITLE
Stats values output ?

### ISSUE THREAD

**Issue by juliencarponcy** [ttumkaya/ContrastPlot_MATLAB#7]
Hello,

Just wanted to know if there is a way of retrieving the same kind of csv output files provided by the web version of the script in matlab.

It is quite annoying to only find group differences and not a single p-value, so I guess I will have to do the copy-paste anyway... Too bad I realized that after scripting my analysis...

Thanks

**Comment by ttumkaya** [comment]
Hi @juliencarponcy,

Thanks for using estimationstats. A similar question was answered in our [Google Group](https://groups.google.com/forum/#!forum/estimationstats). We recommend using the group chat for quicker answers.

Briefly, the DABEST-MATLAB package returns a table object that can be easily written as a .csv output file.

As for the significance testing, we encourage the use of effect sizes and confidence intervals instead; hence, including p values to all the DABEST versions has not been a priority. One way you can obtain these values at the moment would be through our web app.

Best,
Tayfun
